# Generated by Django 3.2.9 on 2021-11-15 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('email', models.EmailField(max_length=160, unique=True, verbose_name='Email')),
                ('telegram_id', models.CharField(max_length=50, unique=True, verbose_name='Telegram Id')),
                ('notify_to_telegram', models.BooleanField(default=True, verbose_name='Send notificaitons to Telegram')),
                ('notify_to_email', models.BooleanField(default=False, verbose_name='Send notifications to email')),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_since', models.DateField(auto_now_add=True, verbose_name='Member since')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('membership_type', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], max_length=25, verbose_name='Membership type')),
                ('valid_thru', models.DateField(blank=True, null=True, verbose_name='Valid thru')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trading_bot.user')),
            ],
        ),
    ]
