# Generated by Django 3.2.9 on 2021-11-15 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('binance', 'Binance'), ('buda', 'Buda'), ('gemini', 'Gemini'), ('bitso', 'Bitso'), ('okcoin', 'OKCoin'), ('bitstamp1', 'Bitstamp')], max_length=100, verbose_name='CCXT exchange id')),
            ],
        ),
        migrations.CreateModel(
            name='UserExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=100, verbose_name='API Secret')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trading_bot.exchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trading_bot.user')),
            ],
        ),
    ]
